//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccountClient.BankAccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amount", Namespace="http://schemas.datacontract.org/2004/07/BankAccountService")]
    [System.SerializableAttribute()]
    public partial class Amount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankAccountService.IBankAccountService")]
    public interface IBankAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/PrintStatements", ReplyAction="http://tempuri.org/IBankAccountService/PrintStatementsResponse")]
        string PrintStatements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/PrintStatements", ReplyAction="http://tempuri.org/IBankAccountService/PrintStatementsResponse")]
        System.Threading.Tasks.Task<string> PrintStatementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/Deposit", ReplyAction="http://tempuri.org/IBankAccountService/DepositResponse")]
        void Deposit(BankAccountClient.BankAccountService.Amount amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/Deposit", ReplyAction="http://tempuri.org/IBankAccountService/DepositResponse")]
        System.Threading.Tasks.Task DepositAsync(BankAccountClient.BankAccountService.Amount amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/Withdraw", ReplyAction="http://tempuri.org/IBankAccountService/WithdrawResponse")]
        void Withdraw(BankAccountClient.BankAccountService.Amount amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/Withdraw", ReplyAction="http://tempuri.org/IBankAccountService/WithdrawResponse")]
        System.Threading.Tasks.Task WithdrawAsync(BankAccountClient.BankAccountService.Amount amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankAccountServiceChannel : BankAccountClient.BankAccountService.IBankAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankAccountServiceClient : System.ServiceModel.ClientBase<BankAccountClient.BankAccountService.IBankAccountService>, BankAccountClient.BankAccountService.IBankAccountService {
        
        public BankAccountServiceClient() {
        }
        
        public BankAccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankAccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PrintStatements() {
            return base.Channel.PrintStatements();
        }
        
        public System.Threading.Tasks.Task<string> PrintStatementsAsync() {
            return base.Channel.PrintStatementsAsync();
        }
        
        public void Deposit(BankAccountClient.BankAccountService.Amount amount) {
            base.Channel.Deposit(amount);
        }
        
        public System.Threading.Tasks.Task DepositAsync(BankAccountClient.BankAccountService.Amount amount) {
            return base.Channel.DepositAsync(amount);
        }
        
        public void Withdraw(BankAccountClient.BankAccountService.Amount amount) {
            base.Channel.Withdraw(amount);
        }
        
        public System.Threading.Tasks.Task WithdrawAsync(BankAccountClient.BankAccountService.Amount amount) {
            return base.Channel.WithdrawAsync(amount);
        }
    }
}
